server:
  port: 9527

spring:
  application:
    name: spring-cloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: SERVICECLOUD-ZUUL
    prefer-ip-address: true

info:
  app.name: servicecloud-zuul
  company.name: lixk
  build.artifactId: $project.artifactId$
  build.version: $project.version$

zuul:
  routes:
    mydept.serviceId: spring-cloud-dept
    mydept.path: /mydept/**
  ignored-services: '*'
  prefix: /lixk
  #ignored-services: spring-cloud-dept